FROM python:3.12-slim

WORKDIR /app

ENV PYTHONPATH=/app

COPY requirements.txt requirements.txt

RUN pip install --no-cache -r requirements.txt

ENTRYPOINT [ "python", "-m", "flask", "--app", "src/app.py", "run", "--host=0.0.0.0" ]

EXPOSE 5000