FROM --platform=linux/amd64 python:3.12-slim

WORKDIR /app

ENV PYTHONPATH=/app

COPY requirements.txt requirements.txt

RUN pip install --no-cache -r requirements.txt

ENTRYPOINT [ "python", "-m", "flask", "--app", "src/app.py", "run", "-h", "0.0.0.0", "-p", "5001" ]

EXPOSE 5001